### ISSUE TITLE
Error downloading the plugin list

### ISSUE THREAD

**Issue by gsegal** [bruderstein/nppPluginManager#57]
### Description of the Issue

Getting the following error message when I click Show Plugin Manager "There was an error downloading the plugin list." Please check your internet connection, and your proxy settings in Internet Explorer, Edge, or Chrome". If I go to %APPDATA%\Roaming\Notepad++\plugins\config and delete PlugInManagerPlugins.xml, then restart NotePad++ it works.

Have been able to reproduce this on 2 machines.

### Steps to Reproduce the Issue

1. Start NotePad++
2. Click Plugins -> Plugin Manager -> Show Plugin Manager. This will work if it is the first time being done that day (or perhaps after a certain time frame).
3. Close NotePad++
4. Restart NotePad++
5. Click Plugins -> Plugin Manager -> Show Plugin Manager. This will result in the error.
6. Close NotePad++
7. Delete %APPDATA%\Roaming\Notepad++\plugins\config and delete PlugInManagerPlugins.xml
8. Restart NotePad++
9. Click Plugins -> Plugin Manager -> Show Plugin Manager. This will work proving that it is not the internet connection or the proxy settings.

### Expected Behavior

Expect Show Plugin Manager to work even if it already has data from that day.

### Actual Behavior

See steps to reproduce the issue.

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll JSMinNPP.dll NppJumpList.dll NppTextFX.dll PluginManager.dll RunMe.dll XMLTools.dll 

PlugIn Manager V1.4.5.0 (also happens in V1.4.3 and V1.4.6)

**Comment by jowells** [comment]
Experiencing the same issue.

**Comment by chcg** [comment]
Seems to be an error in the list provided from the server side, see
[PluginManagerPlugins.txt](https://github.com/bruderstein/nppPluginManager/files/913987/PluginManagerPlugins.txt)

**Comment by bruderstein** [comment]
Fixed!

Thanks for the report - sometimes this happens at the moment, and it's due to the admin system running out of memory/connections/something else.

Unfortunately this happened just as we were exporting an update to the dev list. I've updated the dev list again, so now it's fine again.

Thanks again for the report.

**Comment by gsegal** [comment]
I’m still getting the error. Do I need to do anything on my end to clear it?

Gil Segal
Head of Practice
Sapiens DECISION

Email : gil.segal@sapiens.com<mailto:gil.segal@sapiens.com>
Mobile: (919) 931-5073
Phone: (919) 405-1525

Address: 4000 CentreGreen Way, Suite 150, Cary, NC 27513

Visit us on: www.sapiensdecision.com<http://www.sapiensdecision.com/>
Follow us on: Twitter<https://twitter.com/#!/sapiensins>, LinkedIn<http://www.linkedin.com/company/sapiens>

P Please consider the environment before printing

**Comment by chcg** [comment]
I will work on some other findings of cppcheck.

Starting with:

Zusammenfassung: Memory leak: hashString
Meldung: Memory leak: hashString

in Plugin.cpp line 275.

**Comment by chcg** [comment]
@gsegal 
Which list do you download? Standard one or the DevList? Is it win10 with the creators update?

**Comment by gsegal** [comment]
Standard list, still Win 10 Anniversary Update.

[cid:image001.png@01D2B2E7.F77DC510]

Gil Segal
Head of Practice
Sapiens DECISION

Email : gil.segal@sapiens.com<mailto:gil.segal@sapiens.com>
Mobile: (919) 931-5073
Phone: (919) 405-1525

Address: 4000 CentreGreen Way, Suite 150, Cary, NC 27513

Visit us on: www.sapiensdecision.com<http://www.sapiensdecision.com/>
Follow us on: Twitter<https://twitter.com/#!/sapiensins>, LinkedIn<http://www.linkedin.com/company/sapiens>

P Please consider the environment before printing

**Comment by bruderstein** [comment]
I've found it - fix on the way (it should actually correct itself from the server side, once the caches update), but the _real_ fix is in code.

If it's not able to download within a couple of hours from now, please let me know here.

**Comment by gsegal** [comment]
Confirmed, working now. Thanks!

Gil Segal
Head of Practice
Sapiens DECISION

Email : gil.segal@sapiens.com<mailto:gil.segal@sapiens.com>
Mobile: (919) 931-5073
Phone: (919) 405-1525

Address: 4000 CentreGreen Way, Suite 150, Cary, NC 27513

Visit us on: www.sapiensdecision.com<http://www.sapiensdecision.com/>
Follow us on: Twitter<https://twitter.com/#!/sapiensins>, LinkedIn<http://www.linkedin.com/company/sapiens>

P Please consider the environment before printing

**Comment by ophers** [comment]
This is not fixed for me, unfortunately (tested just now).
I experience the same as @gsegal.

**Comment by jowells** [comment]
It is working for me now

**Comment by bruderstein** [comment]
Great stuff, I've just cut a v1.4.7, but i think there's actually one more small change I need to make so that we can fix the hash on the server - we'll use a different path for the hash from 1.4.8 onwards, then that can be the correct hash, and the old URL can answer with an "incorrect" hash, which actually allows 1.4.3 through 1.4.6 to work.

**Comment by bruderstein** [comment]
Thanks for coming back and letting us know @ophers :+1:

**Comment by jowells** [comment]
Thanks for the quick response and getting it knocked out!

**Comment by bruderstein** [comment]
This is now fixed and finalised in 1.4.8. Thanks for all the help everyone.

**Comment by criskolkman** [comment]
It doesn't seem to be fixed. Just did a fresh install of Notepad++ and added Plugin Manager (shame you have to do it yourself nowadays), but Plugin Manager is not able to get the plugin list.

**Comment by Illuminata** [comment]
Yes, this is still occurring for me as of v1.4.9, N++ v7.5.1

If there's anything I can provide to assist, I'd be happy to.

**Comment by RichardD2** [comment]
Same problem here on a Windows 2008 R2 computer. At exactly the same time, my Windows 10 computer is able to display the list of plugins without any problems.

Trying to open [the plugins2.md5.txt URL](https://nppxml.bruderste.in/pm/xml/plugins2.md5.txt) in Internet Explorer on the computer that doesn't work returns "This page can't be displayed". It suggests turning on TLS 1.0, 1.1 and 1.2, but all three are already enabled.

Changing the settings to force HTTP for downloading the plugin list, and restarting NP++, seems to resolve the issue.

**Comment by chcg** [comment]
@Illuminata @RichardD2 @criskolkman 
- Are you using the 32bit or 64bit versions?
- As  RichardD2 did you could try to download the list with the IE webbrowser and see if TLS 1.0 or greater is working fine. ( the webadresses are defined in https://github.com/bruderstein/nppPluginManager/blob/master/pluginManager/src/PluginManager.h). PluginManager uses the windows library for SSL\TLS (see also #40) like used by IE.

@RichardD2 , see https://support.quovadisglobal.com/kb/a433/how-to-enable-tls-1_2-on-windows-server-2008-r2.aspx

**Comment by RichardD2** [comment]
@chcg TLS 1.0, 1.1 and 1.2 were already enabled. It was the ciphers that were causing the problem. We only had **TLS_ECDHE_RSA_*** enabled, but [your server expects](https://www.ssllabs.com/ssltest/analyze.html?d=nppxml.bruderste.in) **TLS_ECDHE_ECDSA_*** instead.

After using [IIS Crypto](https://www.nartac.com/Products/IISCrypto/) to enable the "best practice" ciphers and rebooting the server, the site is now accessible, and the plugin manager works without the _"force HTTP"_ setting.

**Comment by chcg** [comment]
@RichardD2 See https://www.ssllabs.com/ssltest/analyze.html?d=nppxml.bruderste.in&s=104.18.50.38, seems indeed just ECDSA is allowed and no RSA. Thanks for sharing this info.

**Comment by babzog** [comment]
This is again a problem with npp 7.5.8 32-bit and pluginmanager 1.4.12 on windows 7.  Forcing http does not help.  How would I proceed to solve this?

**Comment by chcg** [comment]
Unfortunately the dev list is broken and would require a correction of the certificate from @bruderstein

**Comment by btrower** [comment]
This happened to me just now for the first time. There is more than one problem with this:
1) There is nothing wrong with the network, so the error message is wrong.
2) Local software should never stop working because it can't reach the network. 
3) Applications should not put up application modal windows unless (literally) the next keystroke would cause unrecoverable damage. In the case of ordinary usage such as (in my case) just opening the app, that means *never* because it should not start up in a state capable of breaking anything. 
The app modal message box on my screen is the *second* one I had to negotiate just opening the program to edit a file locally. It is literally stopping me mid-keystroke *twice* for nothing. 
I have been programming for more than forty years and I am quite, quite clear about points 1, 2, and 3. Don't, don't, don't. 

For the past year, at least I, I have periodically had notepad++ lock up on me so that I had to kill the process with Task Manager. I am not sure that it's a modality problem in that case, but it is similar to the application opening a modal window behind itself so that I can't dismiss it. 

Notepad++ has been my go-to editor for years and it will continue to be, but it is annoying as hell that every few times I open it up I have to kill the process and restart are am stopped cold by a modal window asking me if I want to update. I touch type and I really just want to get editing when I open this application. What were people thinking when they put in something that routinely disables the software until the user attends to something minor and even irrelevant?

Please, anybody who is working on this, find a way to make it so the software does everything it can to do its job as an editor. Just the job. If you have what you consider vital text you just can't stop yourself from displaying put up a red tab on the tab bar so I can at least ignore it while I get on with the task. Microsoft, with its crazy festival of bugs that put errors in the event log, advises users to ignore those errors. They won't ever fix them, but at least they don't actively interfere with your work. Let me at least do that.
